### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by pppipppi** [xifangczy/cat-catch#136]
**bug描述**

**扩展**
 - 版本号

**浏览器**
 - chromium 内核
 - firefox

**涉及网址**

Error: ffmpeg.FS('readFile', 'master.mp4') error. Check if the path exists
    at Object.U [as FS] (https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js:1:11538)
    at startFFmpeg (https://ffmpeg.bmmmd.com/js/ffmpeg.js?v20230221:32:29)

**Comment by xifangczy** [comment]
日志不完整。。
给详细一个操作流程

**Comment by CognitiveBooster** [comment]
无需任何操作, 请耐心等待合并...成功后，自动下载文件
等待... 正在下载FFmpeg
load ffmpeg-core
loading ffmpeg-core
ffmpeg-core loaded
run FS.writeFile memoryVideo <60247320 bytes binary file>
run FS.writeFile memoryAudio <23357002 bytes binary file>
run ffmpeg command: -i memoryAudio -c:a copy audio.aac
ffmpeg version 9e96b1c Copyright (c) 2000-2020 the FFmpeg developers
  built with emcc (Emscripten gcc/clang-like replacement) 2.0.8 (d059fd603d0b45b584f634dc2365bc9e9a6ec1dd)
  configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-x86asm --disable-inline-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --extra-cflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-cxxflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-ldflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1 -L/src/build/lib' --pkg-config-flags=--static --nm=llvm-nm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --enable-gpl --enable-nonfree --enable-zlib --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwavpack --enable-libmp3lame --enable-libfdk-aac --enable-libtheora --enable-libvorbis --enable-libfreetype --enable-libopus --enable-libwebp --enable-libass --enable-libfribidi
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1a658c0] Duplicated SDTP atom
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'memoryAudio':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 1970-01-01T00:00:02.000000Z
  Duration: 00:23:11.41, start: 0.000000, bitrate: 134 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : SoundHandler
Output #0, adts, to 'audio.aac':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    encoder         : Lavf58.45.100
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
size=   22150kB time=00:23:11.38 bitrate= 130.4kbits/s speed=6.11e+03x    
video:0kB audio:21741kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.884158%
FFMPEG_END
run FS.readFile audio.aac
run ffmpeg command: -i memoryVideo -i audio.aac -c copy ***.mp4
ffmpeg version 9e96b1c Copyright (c) 2000-2020 the FFmpeg developers
  built with emcc (Emscripten gcc/clang-like replacement) 2.0.8 (d059fd603d0b45b584f634dc2365bc9e9a6ec1dd)
  configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-x86asm --disable-inline-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --extra-cflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-cxxflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-ldflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1 -L/src/build/lib' --pkg-config-flags=--static --nm=llvm-nm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --enable-gpl --enable-nonfree --enable-zlib --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwavpack --enable-libmp3lame --enable-libfdk-aac --enable-libtheora --enable-libvorbis --enable-libfreetype --enable-libopus --enable-libwebp --enable-libass --enable-libfribidi
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1a65dc0] Duplicated SDTP atom
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'memoryVideo':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 1970-01-01T00:00:02.000000Z
  Duration: 00:23:11.40, start: 0.003500, bitrate: 346 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 342 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : VideoHandler
      encoder         : dailymotion/hls.js
[aac @ 0x1f85940] Estimating duration from bitrate, this may be inaccurate
Input #1, aac, from 'audio.aac':
  Duration: 00:24:10.90, bitrate: 125 kb/s
    Stream #1:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 125 kb/s
***.mp4: Protocol not found
Conversion failed!
FFMPEG_END
run FS.readFile ***.mp4
Program terminated with exit(1)
Error: ffmpeg.FS('readFile', '***.mp4') error. Check if the path exists
    at Object.U [as FS] (https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js:1:11538)
    at merge (https://ffmpeg.bmmmd.com/js/ffmpeg.js?v20230317:116:29)

**Comment by xifangczy** [comment]
清理 https://ffmpeg.bmmmd.com/ 的缓存
然后再尝试一次
